let tagName = "name"
let tagLanguage = "language"
let tagCountDownEnabled = "countDownEnabled"
let tagStartCountDown = "startCountDown"
let tagBeepSounds = "beepSounds"
let tagTimesUpAction = "timesUpAction"
let tagTimesUpMessage = "timesUpMessage"
let tagTimesUpSound = "timesUpSound"
let tagVibrate = "vibrate"
let tagReminderOnOff = "reminderOnOff"
let tagReminderStyle = "reminderStyle"
let tagRegularReminderInterval = "regularReminderInterval"
let tagRegularReminderMessage = "regularReminderMessage"
let tagReminderCount = "reminderCount"
let tagRemindAt = "remindAt"
let tagRemindMessage = "remindMessage"
let tagCounting = "counting"

let tagGestureControls = "gestureControls"
let tagFontStyle = "fontStyle"
let tagAnimation = "animation"
let tagNightMode = "nightMode"

let tagTrueTime = "trueTime"
let tagAnalogClock = "analogClock"
